# Numpy

We often want to work with arrays of numerical data, for example a list of firing rates. We can store such data using basic Python, more specifically as a list of numbers:

In [8]:
lst_1 = [25, 20, 40, 5]

But these lists are missing a lot of functionality that we find useful for handling numerical data. (You may be used to these from Matlab or R.) For example, suppose you want to multiply each number by 2. We may want the following command to work:

In [9]:
2*lst_1

[25, 20, 40, 5, 25, 20, 40, 5]

Yet its output is not what we are looking for. This is because lists are not *vectorized*: they do not assume that operations should be applied elementwise. Instead we would have to use a command like the one below:

In [10]:
lst_2 = [lst_1[i]*2 for i in range(4)]
lst_2

[50, 40, 80, 10]

To address this and other issue that arise in handling numerical data in Python, we can use `numpy`, which stands for numerical data in Python.

So far, we have exclusively used Python's base functionality. `numpy` is the first example of a package that has been contributed by external users and has to be installed manually. It is, however, integral to Python for basically anyone working with numerical data.

In [11]:
import numpy as np

## One-dimensional arrays: Vectors
The central object of interest for numpy is an *array*, which refers to rectangular data (more on this later). The simplest case of an array is a one-dimensional one, a vector. You can create a vector from a list:

In [12]:
lst_1 = [25, 20, 40, 5]
vec_1 = np.array(lst_1)

In [13]:
vec_1

array([25, 20, 40,  5])

In [14]:
type(vec_1)

numpy.ndarray

We can also turn a vector back into a list:

In [15]:
list(vec_1)

[25, 20, 40, 5]

Using the numpy array, we can now perform mathematical operations in the way we would like (and perhaps expect from e.g. Matlab).

In [16]:
vec_2 = 2*vec_1
vec_2

array([50, 40, 80, 10])

In [17]:
vec_1+vec_2

array([ 75,  60, 120,  15])

In contrast, what happens if we add two lists?

In [18]:
lst_1 + lst_2

[25, 20, 40, 5, 50, 40, 80, 10]

### Differences between lists and vectors
Both lists and vectors can be indexed and we can easily transform an array into a list and vice versa. What are some of their differences?
#### Elementwise operations
We have already covered that arrays have elementwise operations whereas lists do not.
#### Each element must have the same type
Lists can consist of elements with different types:

In [19]:
lst_3 = ['a', 5]
lst_3

['a', 5]

An array, on the other hand, will always have the same data type for each of its elements. If a list with unequal types is converted to an array all its elements are converted to the same data type.

In [20]:
vec_3 = np.array(lst_3)
vec_3

array(['a', '5'], dtype='<U11')

<U21 is the data type corresponding to strings. You usually don't want to rely on this automatic casting functionality and should try to avoid it.

In [21]:
type(vec_3)

numpy.ndarray

How can you print out the type of this vector? Note that `type(vec_3)` gives you the type of the entire object which is a numpy array. Rather you want the type of the individual elements. Try using the autocomplete function to find out.

*Hint* look at what the type information was called above.

In [22]:
vec_3.dtype

dtype('<U11')

We do we not need parentheses after `dtype`? This is because `dtype` is not function, but rather a new type of Python object called an *attribute*. These are like variables, but are limited in scope to specific objects. We will get to know them in more depth in a later lesson.

### Question 1

- Create a numpy array with the elements 3, 7, 10 and divide each element by two
- Create a new array `vec_4` that is the elementwise multiplication of `vec_1` and `vec_2`.
- Create an array `vec_5` that has a `True` value wherever `vec_1` is smaller than or equal to `20` and a `False` value otherwise. *Hint:* This should be possible in a one liner.

In [23]:
array1 = np.array([3,7,10])
array1/2

array([1.5, 3.5, 5. ])

In [24]:
vec_4 = vec_1 * vec_2
vec_4

array([1250,  800, 3200,   50])

In [25]:
vec_5 = vec_1 <= 20
vec_5

array([False,  True, False,  True])

## Two-dimensional arrays: Matrices
Rectangular data in two dimensions is often called a matrix: it consists of observations organized by rows and columns. Basic Python would allow us to store such data using a list of lists:

In [26]:
lst_1 = [
    [1, 2],
    [3, 4],
    [5, 6]
]
lst_1

[[1, 2], [3, 4], [5, 6]]

Yet the already tedious process of computing elementwise operations quickly becomes infeasible in this context. If wanted to multiply each element by two we would have to iterate over the outer list and then the inner set of lists.

In [27]:
lst_2 = [
    [2*it2 for it2 in it] for it in lst_1
]
lst_2

[[2, 4], [6, 8], [10, 12]]

Again we can turn the list of lists into a matrix simply by applying `np.array`:

In [28]:
mat_1 = np.array(lst_1)
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

Now we can apply vectorized operations as previously:

In [29]:
mat_2 = 2*mat_1
mat_2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

How can you find out the number of rows and columns of the matrix? Try googling or exploring the methods using the autocomplete function.

In [30]:
mat_1.shape

(3, 2)

Importantly, numpy, by default, uses elementwise computations. So `*` results in elementwise multiplication, not matrix multiplication.

In [31]:
mat_1*mat_2

array([[ 2,  8],
       [18, 32],
       [50, 72]])

You can run matrix multiplication by using the `@` operator.

In [32]:
mat_3 = np.array([[1,2],[3,4]])
mat_1@mat_3

array([[ 7, 10],
       [15, 22],
       [23, 34]])

### Saving arrays
We can save arrays using `np.save`.

In [ ]:
np.save('mat_1.npy', mat_1)

In [ ]:
mat_1_copy = np.load('mat_1.npy')

In [ ]:
mat_1_copy

## Higher-dimensional arrays

We now load some simulated data, which is stored in the file `ex_array.npy`. Try assigning the data in that file to the variable `arr`.

In [33]:
arr = np.load('ex_array.npy')

Suppose you know that what is stored in this data are spike rates of fifty different neurons for two different conditions and ten repeated measurements. Spike rates are recorded every second for 2000 seconds. How can you figure out how this data is represented in the array?

In [34]:
arr.shape

(2, 10, 50, 2000)

In [35]:
arr.ndim

4

Whereas a vector has one dimension and a matrix has two dimensions, `arr` has four dimensions: the first one specifies the condition, the second one the trial, the third one the neuron, and the fourth one the timepoint. We can also create higher-dimensional arrays directly:

In [36]:
arr_2 = np.array([
    [[2,4,6],
     [1,3,5]],
    [[0.5,1,2],
     [0.75, 1, 1.25]]
])

What is `arr_2.ndim` and `arr_2.shape`?

In [33]:
arr_2.ndim

3

In [37]:
arr_2.shape

(2, 2, 3)

### Data must be rectangular
Importantly numpy only allows for rectangular data. What happens if you create an array from a list of lists with unequal length?

In [35]:
mat = np.array([[1,2],[3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [36]:
mat

NameError: name 'mat' is not defined

### Broadcasting

In general you cannot add two matrices with different shapes:

In [38]:
mat_1.shape

(3, 2)

In [39]:
mat_3 = np.array([
    [1,2,3],
    [1,2,3]
])

In [40]:
mat_1+mat_3

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

Elementwise operations can work between two arrays with unequal shapes:
- If they match everywhere except where one of them has a dimension of length 1
- If they have an unequal number of dimensions, the array with fewer dimensions is appended dimensions of length 1 in the beginning.

In [41]:
np.array([
    [1,2]
]) + np.array([
    [1,2],
    [3,4],
    [5,6]
])

array([[2, 4],
       [4, 6],
       [6, 8]])

The same thing is true for matrices with one column or other elementwise operations.

In [42]:
divisor = np.array([[2], [1], [1]])

In [43]:
divisor.shape

(3, 1)

In [44]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
mat_1 / divisor

array([[0.5, 1. ],
       [3. , 4. ],
       [5. , 6. ]])

In [46]:
vec_4 = np.array([1, 2])

In [47]:
vec_4.shape

(2,)

In [48]:
vec_4+mat_1

array([[2, 4],
       [4, 6],
       [6, 8]])

### Creating some arrays

In [49]:
np.linspace(0, 1, 21)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [50]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [52]:
np.ones((4, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### Question 2

Below we're creating arrays with different shapes. Try predicting for each if elementwise addition would work, what shape the resulting array would have, then try it out and see if you were correct.

In [53]:
arr_1 = np.ones((3,2))
arr_2 = np.ones((2,3))
arr_1 + arr_2

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [54]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,5))
arr_1 + arr_2

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [55]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,1))
arr_1 + arr_2

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [56]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((3,5))
arr_1 + arr_2

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [57]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((4,3))
arr_1 + arr_2

ValueError: operands could not be broadcast together with shapes (4,3,5) (4,3) 

## Summary operations

Summary operations allow you to collapse an array according to a certain summary statistic. For instance, we may want to compute the overall mean firing rate in our experimental data:

In [58]:
arr.mean()

0.8717270073789571

You can also specify the axis along we want to average. For instance, maybe we want to average firing rates across individual trials:

In [59]:
arr.shape

(2, 10, 50, 2000)

In [60]:
arr_across_trials = arr.mean(axis=1)

In [61]:
arr_across_trials.shape

(2, 50, 2000)

The `keepdims` argument means that you don't remove the dimensions you're averaging over, but rather set their length to 1:

In [62]:
arr_across_trials = arr.mean(axis=1, keepdims=True)

In [63]:
arr_across_trials.shape

(2, 1, 50, 2000)

You can average across multiple axes as well. For instance, maybe you want to average across both trials and time:

In [64]:
arr_across_trials_and_time = arr.mean(axis=(1,3))

In [65]:
arr_across_trials_and_time.shape

(2, 50)

### Question 3

- What is the average firing rate across all neurons, times, and trials for each condition?
- (Advanced.) Subtract the average firing rate per time across all neurons, trials, and conditions from the original array.

In [66]:
mean_per_condition = arr.mean(axis=(1,2,3))
mean_per_condition.shape

new_arr = arr - arr.mean(axis=3, keepdims= True)
new_arr

array([[[[-7.00688590e-01,  4.25891874e-02, -7.41298043e-01, ...,
           4.14718632e-01,  1.04691386e+00, -7.77652685e-01],
         [ 1.00568119e+00,  3.06183827e-01,  4.54450893e-01, ...,
          -3.53166873e-01, -5.93903828e-01, -1.82492763e-01],
         [ 4.59796796e-01,  8.21008307e-01,  9.13964819e-01, ...,
          -5.47633280e-01,  7.07070254e-02, -3.19402053e-01],
         ...,
         [-3.41114426e-01, -3.13104230e-01, -2.86115189e-02, ...,
          -3.51396840e-02,  1.67502135e-01,  7.60185947e-01],
         [ 1.13938081e-01, -6.67570042e-01, -2.37529908e-01, ...,
           2.57306423e-01,  7.50760531e-01, -4.41437690e-01],
         [-5.57690268e-01,  7.59463299e-01,  9.22591078e-02, ...,
           4.54657628e-01,  8.23055532e-01, -3.88631203e-01]],

        [[ 4.15208163e-02,  1.63798119e-01, -5.09885184e-01, ...,
           5.46173041e-01,  5.26961558e-01,  4.68263548e-01],
         [-1.61982306e-01,  6.00047083e-02,  3.64808156e-01, ...,
          -2.33516039e

## Indexing

Indexing in vectors works just as in lists:

In [67]:
vec_1

array([25, 20, 40,  5])

In [68]:
vec_1[0]

25

For matrices and higher-dimensional arrays, a single index selects a single row:

In [69]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [70]:
mat_1[0]

array([1, 2])

In [71]:
mat_1[0][1]

2

Instead of using two brackets, you can also separate the row and column index by a comma:

In [81]:
# The following two lines of code are equivalent
print(mat_1[0][0])
print(mat_1[0,0])

1
1


### Slicing

Slicing is a useful way of extracting more than one element. In particular, `j:k` extracts the elements j,...,k-1:

In [72]:
vec = np.arange(10)
print(vec)

[0 1 2 3 4 5 6 7 8 9]


In [88]:
vec[3:7]

array([3, 4, 5, 6])

We can leave either end of the range away and it will default to the beginning and the end of the list, respectively.

In [74]:
vec[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [75]:
vec[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [76]:
vec[:] # What do you think this will do?

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You can therefore also use the colon to select all rows of a matrix and specific columns.

In [77]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [78]:
mat_1[:,0]

array([1, 3, 5])

You can add another colon to specify a step size, similarly to how you would use these three arguments in `range`.

In [79]:
vec[3:7:2]

array([3, 5])

We could still leave away the beginning or the end of the slice:

In [80]:
vec[::2]

array([0, 2, 4, 6, 8])

### Question 4
Predict the output of the following commands:

In [81]:
vec[:4]

array([0, 1, 2, 3])

In [82]:
vec[5:9:2]

array([5, 7])

In [89]:
vec[:7:2]

array([0, 2, 4, 6])

In [90]:
vec[2::2]

array([2, 4, 6, 8])

### Boolean indexing

Do you remember how to create an array that is true if and only if `vec` is smaller than 5?

In [91]:
vec = np.arange(10)
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
selector = vec <= 5
selector

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

You can use these boolean arrays to subset the corresponding true values.

In [93]:
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
vec[selector]

array([0, 1, 2, 3, 4, 5])

In [95]:
vec[vec<=5]

array([0, 1, 2, 3, 4, 5])

You can do the same with matrices:

In [96]:
mat_1 = np.array([[1, 2],
       [3, 4],
       [5, 6]])

In [97]:
mat_1 >= 3

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [98]:
mat_1[mat_1 >= 3]

array([3, 4, 5, 6])

### Questions 5
- Consider the example matrix from above and subset all entries with values between 2 and 4. You can try to do this in one line or do it through multipel lines!

In [105]:
mat_1[(mat_1 >= 2) & (mat_1 <= 4)]

array([2, 3, 4])