# Creating some arrays

We are going to practice creating some arrays. The first method is using numpy's function, linspace:

In [1]:
import numpy as np

In [2]:
np.linspace(0, 1, 21)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

You can also use np.arange to create an array of evenly spaced values within a given interval. 

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You can also change the step size when using arange.

In [4]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

You can also use np.ones to create an array full of 1's of your chosen shape, passed in using a tuple (aka, when you use parentheses).

In [5]:
np.ones((4, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### Question 1

Below we're creating arrays with different shapes. Try predicting for each if elementwise addition would work, what shape the resulting array would have, then try it out and see if you were correct. Write a comment in each cell explaining why the output had a particular shape.

In [ ]:
arr_1 = np.ones((3,2))
arr_2 = np.ones((2,3))
arr_1 + arr_2
#Would not work. Dimensions don't match

In [ ]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,5))
arr_2 + arr_2
#Would work and give an array with shape (4,6,5). It has this shape because the dimension of arr_1 
#with 1 element gets recycled in the addition and the other dimensions match in length

In [ ]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,1))
arr_1 + arr_2
#Would work and give an array with shape (4,6,5). It has this shape because the dimensions of arr_1 and arr_2
#with 1 element get recycled in the addition and the other dimensions are equal in length

In [ ]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((3,5))
arr_1 + arr_2
#Would work and give an array of shape (4,3,5). When broadcasting numpy matches the dimesions from right to left
#Since arr_2 is missing only the left most dimension, numpy stretches it to have (1,3,5), which can be broadcast over arr_1

In [ ]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((4,3))
arr_1 + arr_2
#Would not work. When aligned, the 'rightmost' dimesions do not match when first checked, so error 

## Summary operations

**Note that for this cell, you need to have ex_array.npy saved in the same directory as this notebook.**

Summary operations allow you to collapse an array according to a certain summary statistic. For instance, we may want to compute the overall mean firing rate in our experimental data:

In [16]:
arr = np.load('ex_array.npy')

In [17]:
arr.mean()

0.8717270073789571

You can also specify the axis along we want to average. For instance, maybe we want to average firing rates across individual trials:

In [18]:
arr.shape

(2, 10, 50, 2000)

In [19]:
arr_across_trials = arr.mean(axis=1)

In [20]:
arr_across_trials.shape

(2, 50, 2000)

The `keepdims` argument means that you don't remove the dimensions you're averaging over, but rather set their length to 1:

In [21]:
arr_across_trials = arr.mean(axis=1, keepdims=True)

In [22]:
arr_across_trials.shape

(2, 1, 50, 2000)

You can average across multiple axes as well. For instance, maybe you want to average across both trials and time:

In [23]:
arr_across_trials_and_time = arr.mean(axis=(1,3))

In [24]:
arr_across_trials_and_time.shape

(2, 50)

### Question 2

- What is the average firing rate across all neurons, times, and trials for each condition?
- (Advanced, optional.) Subtract the average firing rate per time across all neurons, trials, and conditions from the original array.

When finished, upload a screenshot of this question onto courseworks.

In [26]:
mean_per_condition = arr.mean(axis=(1,2,3))
mean_per_condition

array([0.98828779, 0.75516623])

In [27]:
new_arr = arr - arr.mean(axis=3, keepdims= True)
new_arr

array([[[[-7.00688590e-01,  4.25891874e-02, -7.41298043e-01, ...,
           4.14718632e-01,  1.04691386e+00, -7.77652685e-01],
         [ 1.00568119e+00,  3.06183827e-01,  4.54450893e-01, ...,
          -3.53166873e-01, -5.93903828e-01, -1.82492763e-01],
         [ 4.59796796e-01,  8.21008307e-01,  9.13964819e-01, ...,
          -5.47633280e-01,  7.07070254e-02, -3.19402053e-01],
         ...,
         [-3.41114426e-01, -3.13104230e-01, -2.86115189e-02, ...,
          -3.51396840e-02,  1.67502135e-01,  7.60185947e-01],
         [ 1.13938081e-01, -6.67570042e-01, -2.37529908e-01, ...,
           2.57306423e-01,  7.50760531e-01, -4.41437690e-01],
         [-5.57690268e-01,  7.59463299e-01,  9.22591078e-02, ...,
           4.54657628e-01,  8.23055532e-01, -3.88631203e-01]],

        [[ 4.15208163e-02,  1.63798119e-01, -5.09885184e-01, ...,
           5.46173041e-01,  5.26961558e-01,  4.68263548e-01],
         [-1.61982306e-01,  6.00047083e-02,  3.64808156e-01, ...,
          -2.33516039e

## Indexing

Indexing in vectors works just as in lists:

In [28]:
#ignore this cell
#initializing the vectors, matrices, and lists here.
lst_1 = [25, 20, 40, 5]
vec_1 = np.array(lst_1)

lst_1 = [
    [1, 2],
    [3, 4],
    [5, 6]
]
mat_1 = np.array(lst_1)
# ignore this cell

In [29]:
vec_1

array([25, 20, 40,  5])

In [30]:
vec_1[0]

25

For matrices and higher-dimensional arrays, a single index selects a single row:

In [31]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
mat_1[0]

array([1, 2])

In [33]:
mat_1[0][1]

2

Instead of using two brackets, you can also separate the row and column index by a comma:

In [34]:
# The following two lines of code are equivalent
print(mat_1[0][0])
print(mat_1[0,0])

1
1


### Slicing

Slicing is a useful way of extracting more than one element. In particular, `j:k` extracts the elements j,...,k-1:

In [35]:
vec = np.arange(10)
print(vec)

[0 1 2 3 4 5 6 7 8 9]


In [36]:
vec[3:7]

array([3, 4, 5, 6])

We can leave either end of the range away and it will default to the beginning and the end of the list, respectively.

In [37]:
vec[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [38]:
vec[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [39]:
vec[:] # What do you think this will do?

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You can therefore also use the colon to select all rows of a matrix and specific columns.

In [40]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
mat_1[:,0]

array([1, 3, 5])

You can add another colon to specify a step size, similarly to how you would use these three arguments in `range`.

In [42]:
print(vec)
vec[3:7:2]

[0 1 2 3 4 5 6 7 8 9]


array([3, 5])

We could still leave away the beginning or the end of the slice:

In [43]:
vec[::2]

array([0, 2, 4, 6, 8])

### Question 3
Predict the output of the following commands. After every output, explain in words using a comment why that was the output. Upload a screenshot of this onto courseworks.

In [ ]:
vec
#An array from 0 to 9. Just printing the original array as is, which was 0 to 9

In [44]:
vec[:4]
#An array of ([0,1,2,3]). Slices the array from the beginning up until the index of 4, exclusive

array([0, 1, 2, 3])

In [45]:
vec[5:9:2]
#An array of ([5,7]). Slices the array from index 5 to the index 9, exclusive, but only includes every other index between

array([5, 7])

In [46]:
vec[:7:2]
#An array of ([0,2,4,6]). Slices the array from the beginning until index 7, exxclusive, but only includes every other index between

array([0, 2, 4, 6])

In [47]:
vec[2::2]
#An array of ([2,4,6,8]). Slices the array from index 2 until the end of the array, but only includes every other index between

array([2, 4, 6, 8])

### Boolean indexing

Do you remember how to create an array that is true if and only if `vec` is smaller than 5?

In [48]:
vec = np.arange(10)
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
selector = vec <= 5
selector

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

You can use these boolean arrays to subset the corresponding true values.

In [50]:
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
vec[selector]

array([0, 1, 2, 3, 4, 5])

In [52]:
vec[vec<=5]

array([0, 1, 2, 3, 4, 5])

You can do the same with matrices:

In [53]:
mat_1 = np.array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
mat_1 >= 3

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [55]:
mat_1[mat_1 >= 3]

array([3, 4, 5, 6])

### Questions 4
- Consider the example matrix from above and subset all entries with values between 2 and 4. You can try to do this in one line or do it through multiple lines! Upload a screenshot onto courseworks once you are done!

In [56]:
mat_1[(mat_1 >= 2) & (mat_1 <= 4)] #assuming values between 2 and 4 is inclusive

array([2, 3, 4])